name: Yakuniy Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-va-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Node.js o'rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fayl yaratish
        run: |
          echo "Loyiha muvaffaqiyatli tekshirildi." > natija.txt
          echo "Ijrochi: ${{ secrets.FOYDALANUVCHI_NOMI2 }}" >> natija.txt

      - name: Secretni tekshirish
        run: |
          if [ "${{ secrets.FOYDALANUVCHI_NOMI2 }}" == "Alisher" ]; then
            echo "Tasdiqlandi!"
          else
            echo "Secret topilmadi!"
            exit 1
          fi

      - name: Natijani saqlash (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: yakuniy-natija
          path: natija.txt
